### PR TITLE
Revert "Incomplete orders with users attached are not garbage."

### PR DESCRIPTION
**Pull request by shioyama**
This reverts commit 173ec342be002ae37d41a70acf3ea3b9bffbaf1e.

### CODE REVIEW

**Comment by shioyama** [comment]
Related: degica/degica-platform#290

**Comment by shioyama** [comment]
@miyazawadegica do you want to check this quickly?

**Comment by miyazawadegica** [comment]
I got it. I'll check this now.

**Comment by shioyama** [comment]
This should solve the problem of discontinued products still being purchasable long after they have been discontinued.

**Comment by miyazawadegica** [comment]
LGTM :+1:

**Comment by shioyama** [comment]
Thanks!

**Pull request merged**
